const fs = require('fs');
const path = require('path');

// Paths
const ROOT_DIR = path.resolve(__dirname, '..');
const PUBLISHED_TOML_PATH = path.join(ROOT_DIR, 'blockchain', 'Published.toml');
const GLOBAL_CONFIG_PATH = path.join(ROOT_DIR, 'global.config.json');
const CLIENT_ENV_PATH = path.join(ROOT_DIR, 'client', '.env');

console.log('🔄 Starting Global Config Synchronization...');

// 1. Read Blockchain Package ID from Published.toml
let packageId = '';
try {
    if (fs.existsSync(PUBLISHED_TOML_PATH)) {
        const tomlContent = fs.readFileSync(PUBLISHED_TOML_PATH, 'utf-8');
        // Simple regex to find original-id in [published.testnet] section
        const match = tomlContent.match(/original-id\s*=\s*"(0x[a-fA-F0-9]+)"/);
        if (match && match[1]) {
            packageId = match[1];
            console.log(`✅ Found Package ID in Published.toml: ${packageId}`);
        } else {
            console.warn('⚠️ Could not parse original-id from Published.toml');
        }
    } else {
        console.warn(`⚠️ Published.toml not found at: ${PUBLISHED_TOML_PATH}`);
    }
} catch (error) {
    console.error('❌ Error reading Published.toml:', error);
}

// 2. Read Global Config
let globalConfig = {};
try {
    if (fs.existsSync(GLOBAL_CONFIG_PATH)) {
        globalConfig = JSON.parse(fs.readFileSync(GLOBAL_CONFIG_PATH, 'utf-8'));
        console.log('✅ Loaded global.config.json');
    }
} catch (error) {
    console.error('❌ Error reading global.config.json:', error);
}

// 3. Prepare Environment Variables
const envVars = {
    // Blockchain
    'VITE_PACKAGE_ID': packageId || process.env.VITE_PACKAGE_ID || '', // Prioritize Published.toml
    'VITE_PREMIUM_CONFIG': globalConfig.blockchain?.premiumConfig || '',
    'VITE_ADMIN_ADDRESS': globalConfig.blockchain?.adminAddress || '',
    'VITE_SUI_NETWORK': globalConfig.network || 'testnet',

    // Walrus
    'VITE_WALRUS_PUBLISHER': globalConfig.walrus?.publisher || '',
    'VITE_WALRUS_AGGREGATOR': globalConfig.walrus?.aggregator || '',

    // Auth
    'VITE_ENOKI_API_KEY': globalConfig.auth?.enokiApiKey || '',
    'VITE_GOOGLE_CLIENT_ID': globalConfig.auth?.googleClientId || '',
};

// 4. Update .env content
try {
    let envContent = '';

    // Read existing .env to preserve comments if possible, or just overwrite for consistency
    // Here we'll overwrite to enforce synchronization strictness as requested

    envContent += `# Auto-generated by scripts/sync-config.js\n`;
    envContent += `# Source: blockchain/Published.toml & global.config.json\n\n`;

    for (const [key, value] of Object.entries(envVars)) {
        envContent += `${key}=${value}\n`;
    }

    fs.writeFileSync(CLIENT_ENV_PATH, envContent);
    console.log(`✅ Updated client/.env successfully!`);

} catch (error) {
    console.error('❌ Failed to update .env:', error);
    process.exit(1);
}

console.log('🎉 Synchronization Complete!');
